### ISSUE TITLE
IDE error after installing plugin

### ISSUE THREAD

**Issue by Cico-source** [WahdanZ/SpockAdb#35]
Hi,

I use Android Studio and Kotlin. When I install the plugin, it gives me an IDE error. The most significant error message is:

com.intellij.diagnostic.PluginException: ID "org.intellij.sdk.action.GroupedActions" is already taken by action "Mark All (null)". Action "null (null)" (Plugin: Spock ADB) cannot use the same ID [Plugin: com.wahdan.com.wahdan.spockAdb]

I hope you can fix it somehow .

**Comment by WahdanZ** [comment]
Could you check version 2.0.2

**Comment by jakoss** [comment]
Same thing here on 2.0.2

**Comment by Jake-Jiang** [comment]
update to 2.0.3 and restart ,woks well

**Comment by Cico-source** [comment]
There are still errors when using plugin. This is just one example. Few things work and other don't.

java.lang.IncompatibleClassChangeError: Method 'com.android.tools.idea.gradle.project.model.AndroidModuleModel com.android.tools.idea.gradle.project.model.AndroidModuleModel.get(org.jetbrains.android.facet.AndroidFacet)' must be InterfaceMethodref constant

![image](https://user-images.githubusercontent.com/84936349/177949194-093f977b-a6b2-48b0-8b2c-17d272360ca7.png)
![image](https://user-images.githubusercontent.com/84936349/177950026-abd349b1-e40a-473b-bd1f-466b97dd23dd.png)

**Comment by CristianSarac** [comment]
Thanks for the quick update , the plugin now shows all the buttons however just like mentioned above it trows errors on some of the actions. 
I have the latest version and when i try to use the unninstall application i get the following error `java.lang.IncompatibleClassChangeError: Method 'com.android.tools.idea.gradle.project.model.AndroidModuleModel com.android.tools.idea.gradle.project.model.AndroidModuleModel.get(org.jetbrains.android.facet.AndroidFacet)' must be InterfaceMethodref constant
	at spock.adb.command.GetApplicationIDCommand.execute(GetApplicationIDCommand.kt:13)
	at spock.adb.AdbControllerImp.getApplicationID(AdbControllerImp.kt:32)
	at spock.adb.AdbControllerImp.access$getApplicationID(AdbControllerImp.kt:20)
	at spock.adb.AdbControllerImp$currentFragment$1.invoke(AdbControllerImp.kt:127)
	at spock.adb.AdbControllerImp$currentFragment$1.invoke(AdbControllerImp.kt:126)
	at spock.adb.AdbControllerImp.execute(AdbControllerImp.kt:368)
	at spock.adb.AdbControllerImp.currentFragment(AdbControllerImp.kt:126)
	at spock.adb.SpockAdbViewer.initPlugin$lambda-14(SpockAdbViewer.kt:178)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by WahdanZ** [comment]
Thanks for let me know I'll work to fix it

**Comment by WahdanZ** [comment]
Fixed — both faults reported in this thread.

The action ID collision (`org.intellij.sdk.action.GroupedActions`) was resolved in 2.0.3; no `org.intellij.sdk` IDs remain in the plugin manifest.

The `IncompatibleClassChangeError` that several of you hit afterwards was a separate problem, tracked in #41 and now also fixed: the application-ID lookup no longer goes through `AndroidModuleModel.get()`.

Closing as resolved — please reopen if you see either on 4.0.3.
